// Code generated by "so bind"; DO NOT EDIT.
// sobind: 48 opaque

package libuv

import "solod.dev/so/c"
var _ c.Char

type Malloc_func func(c.Size) any

type Realloc_func func(any, c.Size) any

type Calloc_func func(c.Size, c.Size) any

type Free_func func(any)

type Alloc_cb func(*Handle_t, c.Size, *Buf_t)

type Read_cb func(*Stream_t, c.SSize, *ConstBuf_t)

type Write_cb func(*Write_t, c.Int)

type Connect_cb func(*Connect_t, c.Int)

type Shutdown_cb func(*Shutdown_t, c.Int)

type Connection_cb func(*Stream_t, c.Int)

type Close_cb func(*Handle_t)

type Poll_cb func(*Poll_t, c.Int, c.Int)

type Timer_cb func(*Timer_t)

type Async_cb func(*Async_t)

type Prepare_cb func(*Prepare_t)

type Check_cb func(*Check_t)

type Idle_cb func(*Idle_t)

type Exit_cb func(*Process_t, int64, c.Int)

type Walk_cb func(*Handle_t, any)

type Fs_cb func(*Fs_t)

type Work_cb func(*Work_t)

type After_work_cb func(*Work_t, c.Int)

type Getaddrinfo_cb func(*Getaddrinfo_t, c.Int, *Addrinfo)

type Getnameinfo_cb func(*Getnameinfo_t, c.Int, *c.ConstChar, *c.ConstChar)

type Random_cb func(*Random_t, c.Int, any, c.Size)

type Fs_event_cb func(*Fs_event_t, *c.ConstChar, c.Int, c.Int)

type Fs_poll_cb func(*Fs_poll_t, c.Int, *ConstStat_t, *ConstStat_t)

type Signal_cb func(*Signal_t, c.Int)

type Udp_send_cb func(*Udp_send_t, c.Int)

type Udp_recv_cb func(*Udp_t, c.SSize, *ConstBuf_t, *ConstSockaddr, c.UInt)

type Thread_cb func(any)

//so:extern struct uv__queue
type Uv__queue struct {
	Next *Uv__queue `c:"next"`
	Prev *Uv__queue `c:"prev"`
}

//so:extern struct uv__work
type Uv__work struct {
	Work func(*Uv__work) `c:"work"`
	Done func(*Uv__work, c.Int) `c:"done"`
	Loop *Loop_s `c:"loop"`
	Wq Uv__queue `c:"wq"`
}

// sobind: opaque struct uv_loop_s, field active_reqs has an anonymous union type
//so:extern struct uv_loop_s
type Loop_s struct {}

//so:extern struct uv__io_s
type Uv__io_s struct {
	Bits uintptr `c:"bits"`
	Pending_queue Uv__queue `c:"pending_queue"`
	Watcher_queue Uv__queue `c:"watcher_queue"`
	Pevents c.UInt `c:"pevents"`
	Events c.UInt `c:"events"`
	Fd c.Int `c:"fd"`
	Rcount c.Int `c:"rcount"`
	Wcount c.Int `c:"wcount"`
}

//so:extern uv__io_t
type Uv__io_t struct {
	Bits uintptr `c:"bits"`
	Pending_queue Uv__queue `c:"pending_queue"`
	Watcher_queue Uv__queue `c:"watcher_queue"`
	Pevents c.UInt `c:"pevents"`
	Events c.UInt `c:"events"`
	Fd c.Int `c:"fd"`
	Rcount c.Int `c:"rcount"`
	Wcount c.Int `c:"wcount"`
}

//so:extern uv_buf_t
type Buf_t struct {
	Base *c.Char `c:"base"`
	Len c.Size `c:"len"`
}

//so:extern uv_once_t
type Once_t struct {
	__sig c.Long
	__opaque [8]c.Char
}

//so:extern uv_mutex_t
type Mutex_t struct {
	__sig c.Long
	__opaque [56]c.Char
}

//so:extern uv_rwlock_t
type Rwlock_t struct {
	__sig c.Long
	__opaque [192]c.Char
}

//so:extern uv_cond_t
type Cond_t struct {
	__sig c.Long
	__opaque [40]c.Char
}

//so:extern struct _uv_barrier
type _uv_barrier struct {
	Mutex Mutex_t `c:"mutex"`
	Cond Cond_t `c:"cond"`
	Threshold c.UInt `c:"threshold"`
	In c.UInt `c:"in"`
	Out c.UInt `c:"out"`
}

//so:extern uv_barrier_t
type Barrier_t struct {
	B *_uv_barrier `c:"b"`
}

//so:extern uv__dirent_t
type Uv__dirent_t struct {
	D_ino c.ULongLong `c:"d_ino"`
	D_seekoff c.ULongLong `c:"d_seekoff"`
	D_reclen c.UShort `c:"d_reclen"`
	D_namlen c.UShort `c:"d_namlen"`
	D_type c.UChar `c:"d_type"`
	D_name [1024]c.Char `c:"d_name"`
}

//so:extern uv_lib_t
type Lib_t struct {
	Handle any `c:"handle"`
	Errmsg *c.Char `c:"errmsg"`
}

// sobind: opaque uv_loop_t, field active_reqs has an anonymous union type
//so:extern uv_loop_t
type Loop_t struct {}

// sobind: opaque uv_handle_t, field u has an anonymous union type
//so:extern uv_handle_t
type Handle_t struct {}

//so:extern uv_dir_t
type Dir_t struct {
	Dirents *Dirent_t `c:"dirents"`
	Nentries c.Size `c:"nentries"`
	Reserved [4]any `c:"reserved"`
	Dir *DIR `c:"dir"`
}

//so:extern uv_dirent_t
type Dirent_t struct {
	Name *c.Char `c:"name"`
	Type c.Int `c:"type"`
}

// sobind: opaque DIR, declared outside the binding
//so:extern DIR
type DIR struct {}

// sobind: opaque uv_stream_t, field u has an anonymous union type
//so:extern uv_stream_t
type Stream_t struct {}

// sobind: opaque uv_tcp_t, field u has an anonymous union type
//so:extern uv_tcp_t
type Tcp_t struct {}

// sobind: opaque uv_udp_t, field u has an anonymous union type
//so:extern uv_udp_t
type Udp_t struct {}

// sobind: opaque uv_pipe_t, field u has an anonymous union type
//so:extern uv_pipe_t
type Pipe_t struct {}

// sobind: opaque uv_tty_t, field u has an anonymous union type
//so:extern uv_tty_t
type Tty_t struct {}

// sobind: opaque uv_poll_t, field u has an anonymous union type
//so:extern uv_poll_t
type Poll_t struct {}

// sobind: opaque uv_timer_t, field u has an anonymous union type
//so:extern uv_timer_t
type Timer_t struct {}

// sobind: opaque uv_prepare_t, field u has an anonymous union type
//so:extern uv_prepare_t
type Prepare_t struct {}

// sobind: opaque uv_check_t, field u has an anonymous union type
//so:extern uv_check_t
type Check_t struct {}

// sobind: opaque uv_idle_t, field u has an anonymous union type
//so:extern uv_idle_t
type Idle_t struct {}

// sobind: opaque uv_async_t, field u has an anonymous union type
//so:extern uv_async_t
type Async_t struct {}

// sobind: opaque uv_process_t, field u has an anonymous union type
//so:extern uv_process_t
type Process_t struct {}

// sobind: opaque uv_fs_event_t, field u has an anonymous union type
//so:extern uv_fs_event_t
type Fs_event_t struct {}

// sobind: opaque uv_fs_poll_t, field u has an anonymous union type
//so:extern uv_fs_poll_t
type Fs_poll_t struct {}

// sobind: opaque uv_signal_t, field u has an anonymous union type
//so:extern uv_signal_t
type Signal_t struct {}

//so:extern uv_req_t
type Req_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
}

//so:extern uv_getaddrinfo_t
type Getaddrinfo_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Work_req Uv__work `c:"work_req"`
	Cb func(*Getaddrinfo_t, c.Int, *Addrinfo) `c:"cb"`
	Hints *Addrinfo `c:"hints"`
	Hostname *c.Char `c:"hostname"`
	Service *c.Char `c:"service"`
	Addrinfo *Addrinfo `c:"addrinfo"`
	Retcode c.Int `c:"retcode"`
}

// sobind: opaque struct addrinfo, declared outside the binding
//so:extern struct addrinfo
type Addrinfo struct {}

//so:extern uv_getnameinfo_t
type Getnameinfo_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Work_req Uv__work `c:"work_req"`
	Getnameinfo_cb func(*Getnameinfo_t, c.Int, *c.ConstChar, *c.ConstChar) `c:"getnameinfo_cb"`
	Storage Sockaddr_storage `c:"storage"`
	Flags c.Int `c:"flags"`
	Host [1025]c.Char `c:"host"`
	Service [32]c.Char `c:"service"`
	Retcode c.Int `c:"retcode"`
}

// sobind: opaque struct sockaddr_storage, declared outside the binding
//so:extern struct sockaddr_storage
type Sockaddr_storage struct {}

//so:extern uv_shutdown_t
type Shutdown_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Handle *Stream_t `c:"handle"`
	Cb func(*Shutdown_t, c.Int) `c:"cb"`
}

//so:extern uv_write_t
type Write_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Cb func(*Write_t, c.Int) `c:"cb"`
	Send_handle *Stream_t `c:"send_handle"`
	Handle *Stream_t `c:"handle"`
	Queue Uv__queue `c:"queue"`
	Write_index c.UInt `c:"write_index"`
	Bufs *Buf_t `c:"bufs"`
	Nbufs c.UInt `c:"nbufs"`
	Error c.Int `c:"error"`
	Bufsml [4]Buf_t `c:"bufsml"`
}

//so:extern uv_connect_t
type Connect_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Cb func(*Connect_t, c.Int) `c:"cb"`
	Handle *Stream_t `c:"handle"`
	Queue Uv__queue `c:"queue"`
}

// sobind: opaque uv_udp_send_t, field u has an anonymous union type
//so:extern uv_udp_send_t
type Udp_send_t struct {}

//so:extern uv_fs_t
type Fs_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Fs_type c.Int `c:"fs_type"`
	Loop *Loop_t `c:"loop"`
	Cb func(*Fs_t) `c:"cb"`
	Result c.SSize `c:"result"`
	Ptr any `c:"ptr"`
	Path *c.Char `c:"path"`
	Statbuf Stat_t `c:"statbuf"`
	New_path *c.Char `c:"new_path"`
	File c.Int `c:"file"`
	Flags c.Int `c:"flags"`
	Mode c.UShort `c:"mode"`
	Nbufs c.UInt `c:"nbufs"`
	Bufs *Buf_t `c:"bufs"`
	Off c.LongLong `c:"off"`
	Uid c.UInt `c:"uid"`
	Gid c.UInt `c:"gid"`
	Atime float64 `c:"atime"`
	Mtime float64 `c:"mtime"`
	Work_req Uv__work `c:"work_req"`
	Bufsml [4]Buf_t `c:"bufsml"`
}

//so:extern uv_stat_t
type Stat_t struct {
	St_dev uint64 `c:"st_dev"`
	St_mode uint64 `c:"st_mode"`
	St_nlink uint64 `c:"st_nlink"`
	St_uid uint64 `c:"st_uid"`
	St_gid uint64 `c:"st_gid"`
	St_rdev uint64 `c:"st_rdev"`
	St_ino uint64 `c:"st_ino"`
	St_size uint64 `c:"st_size"`
	St_blksize uint64 `c:"st_blksize"`
	St_blocks uint64 `c:"st_blocks"`
	St_flags uint64 `c:"st_flags"`
	St_gen uint64 `c:"st_gen"`
	St_atim Timespec_t `c:"st_atim"`
	St_mtim Timespec_t `c:"st_mtim"`
	St_ctim Timespec_t `c:"st_ctim"`
	St_birthtim Timespec_t `c:"st_birthtim"`
}

//so:extern uv_timespec_t
type Timespec_t struct {
	Tv_sec c.Long `c:"tv_sec"`
	Tv_nsec c.Long `c:"tv_nsec"`
}

//so:extern uv_work_t
type Work_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Work_cb func(*Work_t) `c:"work_cb"`
	After_work_cb func(*Work_t, c.Int) `c:"after_work_cb"`
	Work_req Uv__work `c:"work_req"`
}

//so:extern uv_random_t
type Random_t struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Status c.Int `c:"status"`
	Buf any `c:"buf"`
	Buflen c.Size `c:"buflen"`
	Cb func(*Random_t, c.Int, any, c.Size) `c:"cb"`
	Work_req Uv__work `c:"work_req"`
}

//so:extern uv_env_item_t
type Env_item_t struct {
	Name *c.Char `c:"name"`
	Value *c.Char `c:"value"`
}

//so:extern uv_cpu_info_t
type Cpu_info_t struct {
	Model *c.Char `c:"model"`
	Speed c.Int `c:"speed"`
	Cpu_times Cpu_times_s `c:"cpu_times"`
}

//so:extern struct uv_cpu_times_s
type Cpu_times_s struct {
	User uint64 `c:"user"`
	Nice uint64 `c:"nice"`
	Sys uint64 `c:"sys"`
	Idle uint64 `c:"idle"`
	Irq uint64 `c:"irq"`
}

// sobind: opaque uv_interface_address_t, field address has an anonymous union type
//so:extern uv_interface_address_t
type Interface_address_t struct {}

//so:extern uv_passwd_t
type Passwd_t struct {
	Username *c.Char `c:"username"`
	Uid c.ULong `c:"uid"`
	Gid c.ULong `c:"gid"`
	Shell *c.Char `c:"shell"`
	Homedir *c.Char `c:"homedir"`
}

//so:extern uv_group_t
type Group_t struct {
	Groupname *c.Char `c:"groupname"`
	Gid c.ULong `c:"gid"`
	Members **c.Char `c:"members"`
}

//so:extern uv_utsname_t
type Utsname_t struct {
	Sysname [256]c.Char `c:"sysname"`
	Release [256]c.Char `c:"release"`
	Version [256]c.Char `c:"version"`
	Machine [256]c.Char `c:"machine"`
}

//so:extern uv_statfs_t
type Statfs_t struct {
	F_type uint64 `c:"f_type"`
	F_bsize uint64 `c:"f_bsize"`
	F_blocks uint64 `c:"f_blocks"`
	F_bfree uint64 `c:"f_bfree"`
	F_bavail uint64 `c:"f_bavail"`
	F_files uint64 `c:"f_files"`
	F_ffree uint64 `c:"f_ffree"`
	F_frsize uint64 `c:"f_frsize"`
	F_spare [3]uint64 `c:"f_spare"`
}

//so:extern uv_metrics_t
type Metrics_t struct {
	Loop_count uint64 `c:"loop_count"`
	Events uint64 `c:"events"`
	Events_waiting uint64 `c:"events_waiting"`
	Reserved [13]*uint64 `c:"reserved"`
}

//so:extern const uv_buf_t
type ConstBuf_t struct {
	Base *c.Char `c:"base"`
	Len c.Size `c:"len"`
}

//so:extern uv_timespec64_t
type Timespec64_t struct {
	Tv_sec int64 `c:"tv_sec"`
	Tv_nsec int32 `c:"tv_nsec"`
}

//so:extern uv_timeval_t
type Timeval_t struct {
	Tv_sec c.Long `c:"tv_sec"`
	Tv_usec c.Long `c:"tv_usec"`
}

//so:extern uv_timeval64_t
type Timeval64_t struct {
	Tv_sec int64 `c:"tv_sec"`
	Tv_usec int32 `c:"tv_usec"`
}

//so:extern const uv_stat_t
type ConstStat_t struct {
	St_dev uint64 `c:"st_dev"`
	St_mode uint64 `c:"st_mode"`
	St_nlink uint64 `c:"st_nlink"`
	St_uid uint64 `c:"st_uid"`
	St_gid uint64 `c:"st_gid"`
	St_rdev uint64 `c:"st_rdev"`
	St_ino uint64 `c:"st_ino"`
	St_size uint64 `c:"st_size"`
	St_blksize uint64 `c:"st_blksize"`
	St_blocks uint64 `c:"st_blocks"`
	St_flags uint64 `c:"st_flags"`
	St_gen uint64 `c:"st_gen"`
	St_atim Timespec_t `c:"st_atim"`
	St_mtim Timespec_t `c:"st_mtim"`
	St_ctim Timespec_t `c:"st_ctim"`
	St_birthtim Timespec_t `c:"st_birthtim"`
}

//so:extern struct uv_req_s
type Req_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
}

//so:extern struct uv_shutdown_s
type Shutdown_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Handle *Stream_t `c:"handle"`
	Cb func(*Shutdown_t, c.Int) `c:"cb"`
}

// sobind: opaque struct uv_handle_s, field u has an anonymous union type
//so:extern struct uv_handle_s
type Handle_s struct {}

// sobind: opaque FILE, declared outside the binding
//so:extern FILE
type FILE struct {}

// sobind: opaque struct uv_stream_s, field u has an anonymous union type
//so:extern struct uv_stream_s
type Stream_s struct {}

//so:extern struct uv_write_s
type Write_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Cb func(*Write_t, c.Int) `c:"cb"`
	Send_handle *Stream_t `c:"send_handle"`
	Handle *Stream_t `c:"handle"`
	Queue Uv__queue `c:"queue"`
	Write_index c.UInt `c:"write_index"`
	Bufs *Buf_t `c:"bufs"`
	Nbufs c.UInt `c:"nbufs"`
	Error c.Int `c:"error"`
	Bufsml [4]Buf_t `c:"bufsml"`
}

// sobind: opaque struct uv_tcp_s, field u has an anonymous union type
//so:extern struct uv_tcp_s
type Tcp_s struct {}

// sobind: opaque struct sockaddr, declared outside the binding
//so:extern struct sockaddr
type Sockaddr struct {}

//so:extern struct uv_connect_s
type Connect_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Cb func(*Connect_t, c.Int) `c:"cb"`
	Handle *Stream_t `c:"handle"`
	Queue Uv__queue `c:"queue"`
}

// sobind: opaque const struct sockaddr, declared outside the binding
//so:extern const struct sockaddr
type ConstSockaddr struct {}

// sobind: opaque struct uv_udp_s, field u has an anonymous union type
//so:extern struct uv_udp_s
type Udp_s struct {}

// sobind: opaque struct uv_udp_send_s, field u has an anonymous union type
//so:extern struct uv_udp_send_s
type Udp_send_s struct {}

// sobind: opaque struct uv_tty_s, field u has an anonymous union type
//so:extern struct uv_tty_s
type Tty_s struct {}

// sobind: opaque struct uv_pipe_s, field u has an anonymous union type
//so:extern struct uv_pipe_s
type Pipe_s struct {}

// sobind: opaque struct uv_poll_s, field u has an anonymous union type
//so:extern struct uv_poll_s
type Poll_s struct {}

// sobind: opaque struct uv_prepare_s, field u has an anonymous union type
//so:extern struct uv_prepare_s
type Prepare_s struct {}

// sobind: opaque struct uv_check_s, field u has an anonymous union type
//so:extern struct uv_check_s
type Check_s struct {}

// sobind: opaque struct uv_idle_s, field u has an anonymous union type
//so:extern struct uv_idle_s
type Idle_s struct {}

// sobind: opaque struct uv_async_s, field u has an anonymous union type
//so:extern struct uv_async_s
type Async_s struct {}

// sobind: opaque struct uv_timer_s, field u has an anonymous union type
//so:extern struct uv_timer_s
type Timer_s struct {}

//so:extern struct uv_getaddrinfo_s
type Getaddrinfo_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Work_req Uv__work `c:"work_req"`
	Cb func(*Getaddrinfo_t, c.Int, *Addrinfo) `c:"cb"`
	Hints *Addrinfo `c:"hints"`
	Hostname *c.Char `c:"hostname"`
	Service *c.Char `c:"service"`
	Addrinfo *Addrinfo `c:"addrinfo"`
	Retcode c.Int `c:"retcode"`
}

//so:extern struct uv_getnameinfo_s
type Getnameinfo_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Work_req Uv__work `c:"work_req"`
	Getnameinfo_cb func(*Getnameinfo_t, c.Int, *c.ConstChar, *c.ConstChar) `c:"getnameinfo_cb"`
	Storage Sockaddr_storage `c:"storage"`
	Flags c.Int `c:"flags"`
	Host [1025]c.Char `c:"host"`
	Service [32]c.Char `c:"service"`
	Retcode c.Int `c:"retcode"`
}

// sobind: opaque uv_stdio_container_t, field data has an anonymous union type
//so:extern uv_stdio_container_t
type Stdio_container_t struct {}

//so:extern uv_process_options_t
type Process_options_t struct {
	Exit_cb func(*Process_t, int64, c.Int) `c:"exit_cb"`
	File *c.Char `c:"file"`
	Args **c.Char `c:"args"`
	Env **c.Char `c:"env"`
	Cwd *c.Char `c:"cwd"`
	Flags c.UInt `c:"flags"`
	Stdio_count c.Int `c:"stdio_count"`
	Stdio *Stdio_container_t `c:"stdio"`
	Uid c.UInt `c:"uid"`
	Gid c.UInt `c:"gid"`
}

// sobind: opaque struct uv_process_s, field u has an anonymous union type
//so:extern struct uv_process_s
type Process_s struct {}

//so:extern struct uv_work_s
type Work_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Work_cb func(*Work_t) `c:"work_cb"`
	After_work_cb func(*Work_t, c.Int) `c:"after_work_cb"`
	Work_req Uv__work `c:"work_req"`
}

//so:extern struct uv_cpu_info_s
type Cpu_info_s struct {
	Model *c.Char `c:"model"`
	Speed c.Int `c:"speed"`
	Cpu_times Cpu_times_s `c:"cpu_times"`
}

// sobind: opaque struct uv_interface_address_s, field address has an anonymous union type
//so:extern struct uv_interface_address_s
type Interface_address_s struct {}

//so:extern struct uv_passwd_s
type Passwd_s struct {
	Username *c.Char `c:"username"`
	Uid c.ULong `c:"uid"`
	Gid c.ULong `c:"gid"`
	Shell *c.Char `c:"shell"`
	Homedir *c.Char `c:"homedir"`
}

//so:extern struct uv_group_s
type Group_s struct {
	Groupname *c.Char `c:"groupname"`
	Gid c.ULong `c:"gid"`
	Members **c.Char `c:"members"`
}

//so:extern struct uv_utsname_s
type Utsname_s struct {
	Sysname [256]c.Char `c:"sysname"`
	Release [256]c.Char `c:"release"`
	Version [256]c.Char `c:"version"`
	Machine [256]c.Char `c:"machine"`
}

//so:extern struct uv_statfs_s
type Statfs_s struct {
	F_type uint64 `c:"f_type"`
	F_bsize uint64 `c:"f_bsize"`
	F_blocks uint64 `c:"f_blocks"`
	F_bfree uint64 `c:"f_bfree"`
	F_bavail uint64 `c:"f_bavail"`
	F_files uint64 `c:"f_files"`
	F_ffree uint64 `c:"f_ffree"`
	F_frsize uint64 `c:"f_frsize"`
	F_spare [3]uint64 `c:"f_spare"`
}

//so:extern struct uv_dirent_s
type Dirent_s struct {
	Name *c.Char `c:"name"`
	Type c.Int `c:"type"`
}

//so:extern uv_rusage_t
type Rusage_t struct {
	Ru_utime Timeval_t `c:"ru_utime"`
	Ru_stime Timeval_t `c:"ru_stime"`
	Ru_maxrss uint64 `c:"ru_maxrss"`
	Ru_ixrss uint64 `c:"ru_ixrss"`
	Ru_idrss uint64 `c:"ru_idrss"`
	Ru_isrss uint64 `c:"ru_isrss"`
	Ru_minflt uint64 `c:"ru_minflt"`
	Ru_majflt uint64 `c:"ru_majflt"`
	Ru_nswap uint64 `c:"ru_nswap"`
	Ru_inblock uint64 `c:"ru_inblock"`
	Ru_oublock uint64 `c:"ru_oublock"`
	Ru_msgsnd uint64 `c:"ru_msgsnd"`
	Ru_msgrcv uint64 `c:"ru_msgrcv"`
	Ru_nsignals uint64 `c:"ru_nsignals"`
	Ru_nvcsw uint64 `c:"ru_nvcsw"`
	Ru_nivcsw uint64 `c:"ru_nivcsw"`
}

// sobind: opaque struct _opaque_pthread_t, declared outside the binding
//so:extern struct _opaque_pthread_t
type _opaque_pthread_t struct {}

//so:extern struct uv_env_item_s
type Env_item_s struct {
	Name *c.Char `c:"name"`
	Value *c.Char `c:"value"`
}

//so:extern struct uv_metrics_s
type Metrics_s struct {
	Loop_count uint64 `c:"loop_count"`
	Events uint64 `c:"events"`
	Events_waiting uint64 `c:"events_waiting"`
	Reserved [13]*uint64 `c:"reserved"`
}

//so:extern struct uv_dir_s
type Dir_s struct {
	Dirents *Dirent_t `c:"dirents"`
	Nentries c.Size `c:"nentries"`
	Reserved [4]any `c:"reserved"`
	Dir *DIR `c:"dir"`
}

//so:extern struct uv_fs_s
type Fs_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Fs_type c.Int `c:"fs_type"`
	Loop *Loop_t `c:"loop"`
	Cb func(*Fs_t) `c:"cb"`
	Result c.SSize `c:"result"`
	Ptr any `c:"ptr"`
	Path *c.Char `c:"path"`
	Statbuf Stat_t `c:"statbuf"`
	New_path *c.Char `c:"new_path"`
	File c.Int `c:"file"`
	Flags c.Int `c:"flags"`
	Mode c.UShort `c:"mode"`
	Nbufs c.UInt `c:"nbufs"`
	Bufs *Buf_t `c:"bufs"`
	Off c.LongLong `c:"off"`
	Uid c.UInt `c:"uid"`
	Gid c.UInt `c:"gid"`
	Atime float64 `c:"atime"`
	Mtime float64 `c:"mtime"`
	Work_req Uv__work `c:"work_req"`
	Bufsml [4]Buf_t `c:"bufsml"`
}

// sobind: opaque struct uv_fs_event_s, field u has an anonymous union type
//so:extern struct uv_fs_event_s
type Fs_event_s struct {}

// sobind: opaque struct uv_fs_poll_s, field u has an anonymous union type
//so:extern struct uv_fs_poll_s
type Fs_poll_s struct {}

// sobind: opaque struct uv_signal_s, field u has an anonymous union type
//so:extern struct uv_signal_s
type Signal_s struct {}

// sobind: opaque struct sockaddr_in, declared outside the binding
//so:extern struct sockaddr_in
type Sockaddr_in struct {}

// sobind: opaque struct sockaddr_in6, declared outside the binding
//so:extern struct sockaddr_in6
type Sockaddr_in6 struct {}

//so:extern struct uv_random_s
type Random_s struct {
	Data any `c:"data"`
	Type c.Int `c:"type"`
	Reserved [6]any `c:"reserved"`
	Loop *Loop_t `c:"loop"`
	Status c.Int `c:"status"`
	Buf any `c:"buf"`
	Buflen c.Size `c:"buflen"`
	Cb func(*Random_t, c.Int, any, c.Size) `c:"cb"`
	Work_req Uv__work `c:"work_req"`
}

//so:extern struct uv_thread_options_s
type Thread_options_s struct {
	Flags c.UInt `c:"flags"`
	Stack_size c.Size `c:"stack_size"`
}

//so:extern uv_thread_options_t
type Thread_options_t struct {
	Flags c.UInt `c:"flags"`
	Stack_size c.Size `c:"stack_size"`
}

//so:extern union uv_any_handle
type Any_handle struct {
	Async Async_t `c:"async"`
	Check Check_t `c:"check"`
	Fs_event Fs_event_t `c:"fs_event"`
	Fs_poll Fs_poll_t `c:"fs_poll"`
	Handle Handle_t `c:"handle"`
	Idle Idle_t `c:"idle"`
	Pipe Pipe_t `c:"pipe"`
	Poll Poll_t `c:"poll"`
	Prepare Prepare_t `c:"prepare"`
	Process Process_t `c:"process"`
	Stream Stream_t `c:"stream"`
	Tcp Tcp_t `c:"tcp"`
	Timer Timer_t `c:"timer"`
	Tty Tty_t `c:"tty"`
	Udp Udp_t `c:"udp"`
	Signal Signal_t `c:"signal"`
}

//so:extern union uv_any_req
type Any_req struct {
	Req Req_t `c:"req"`
	Connect Connect_t `c:"connect"`
	Write Write_t `c:"write"`
	Shutdown Shutdown_t `c:"shutdown"`
	Udp_send Udp_send_t `c:"udp_send"`
	Fs Fs_t `c:"fs"`
	Work Work_t `c:"work"`
	Getaddrinfo Getaddrinfo_t `c:"getaddrinfo"`
	Getnameinfo Getnameinfo_t `c:"getnameinfo"`
	Random Random_t `c:"random"`
}

//so:extern UV_E2BIG
const E2BIG = -7

//so:extern UV_EACCES
const EACCES = -13

//so:extern UV_EADDRINUSE
const EADDRINUSE = -48

//so:extern UV_EADDRNOTAVAIL
const EADDRNOTAVAIL = -49

//so:extern UV_EAFNOSUPPORT
const EAFNOSUPPORT = -47

//so:extern UV_EAGAIN
const EAGAIN = -35

//so:extern UV_EAI_ADDRFAMILY
const EAI_ADDRFAMILY = -3000

//so:extern UV_EAI_AGAIN
const EAI_AGAIN = -3001

//so:extern UV_EAI_BADFLAGS
const EAI_BADFLAGS = -3002

//so:extern UV_EAI_BADHINTS
const EAI_BADHINTS = -3013

//so:extern UV_EAI_CANCELED
const EAI_CANCELED = -3003

//so:extern UV_EAI_FAIL
const EAI_FAIL = -3004

//so:extern UV_EAI_FAMILY
const EAI_FAMILY = -3005

//so:extern UV_EAI_MEMORY
const EAI_MEMORY = -3006

//so:extern UV_EAI_NODATA
const EAI_NODATA = -3007

//so:extern UV_EAI_NONAME
const EAI_NONAME = -3008

//so:extern UV_EAI_OVERFLOW
const EAI_OVERFLOW = -3009

//so:extern UV_EAI_PROTOCOL
const EAI_PROTOCOL = -3014

//so:extern UV_EAI_SERVICE
const EAI_SERVICE = -3010

//so:extern UV_EAI_SOCKTYPE
const EAI_SOCKTYPE = -3011

//so:extern UV_EALREADY
const EALREADY = -37

//so:extern UV_EBADF
const EBADF = -9

//so:extern UV_EBUSY
const EBUSY = -16

//so:extern UV_ECANCELED
const ECANCELED = -89

//so:extern UV_ECHARSET
const ECHARSET = -4080

//so:extern UV_ECONNABORTED
const ECONNABORTED = -53

//so:extern UV_ECONNREFUSED
const ECONNREFUSED = -61

//so:extern UV_ECONNRESET
const ECONNRESET = -54

//so:extern UV_EDESTADDRREQ
const EDESTADDRREQ = -39

//so:extern UV_EEXIST
const EEXIST = -17

//so:extern UV_EFAULT
const EFAULT = -14

//so:extern UV_EFBIG
const EFBIG = -27

//so:extern UV_EHOSTUNREACH
const EHOSTUNREACH = -65

//so:extern UV_EINTR
const EINTR = -4

//so:extern UV_EINVAL
const EINVAL = -22

//so:extern UV_EIO
const EIO = -5

//so:extern UV_EISCONN
const EISCONN = -56

//so:extern UV_EISDIR
const EISDIR = -21

//so:extern UV_ELOOP
const ELOOP = -62

//so:extern UV_EMFILE
const EMFILE = -24

//so:extern UV_EMSGSIZE
const EMSGSIZE = -40

//so:extern UV_ENAMETOOLONG
const ENAMETOOLONG = -63

//so:extern UV_ENETDOWN
const ENETDOWN = -50

//so:extern UV_ENETUNREACH
const ENETUNREACH = -51

//so:extern UV_ENFILE
const ENFILE = -23

//so:extern UV_ENOBUFS
const ENOBUFS = -55

//so:extern UV_ENODEV
const ENODEV = -19

//so:extern UV_ENOENT
const ENOENT = -2

//so:extern UV_ENOMEM
const ENOMEM = -12

//so:extern UV_ENONET
const ENONET = -4056

//so:extern UV_ENOPROTOOPT
const ENOPROTOOPT = -42

//so:extern UV_ENOSPC
const ENOSPC = -28

//so:extern UV_ENOSYS
const ENOSYS = -78

//so:extern UV_ENOTCONN
const ENOTCONN = -57

//so:extern UV_ENOTDIR
const ENOTDIR = -20

//so:extern UV_ENOTEMPTY
const ENOTEMPTY = -66

//so:extern UV_ENOTSOCK
const ENOTSOCK = -38

//so:extern UV_ENOTSUP
const ENOTSUP = -45

//so:extern UV_EOVERFLOW
const EOVERFLOW = -84

//so:extern UV_EPERM
const EPERM = -1

//so:extern UV_EPIPE
const EPIPE = -32

//so:extern UV_EPROTO
const EPROTO = -100

//so:extern UV_EPROTONOSUPPORT
const EPROTONOSUPPORT = -43

//so:extern UV_EPROTOTYPE
const EPROTOTYPE = -41

//so:extern UV_ERANGE
const ERANGE = -34

//so:extern UV_EROFS
const EROFS = -30

//so:extern UV_ESHUTDOWN
const ESHUTDOWN = -58

//so:extern UV_ESPIPE
const ESPIPE = -29

//so:extern UV_ESRCH
const ESRCH = -3

//so:extern UV_ETIMEDOUT
const ETIMEDOUT = -60

//so:extern UV_ETXTBSY
const ETXTBSY = -26

//so:extern UV_EXDEV
const EXDEV = -18

//so:extern UV_UNKNOWN
const UNKNOWN = -4094

//so:extern UV_EOF
const EOF = -4095

//so:extern UV_ENXIO
const ENXIO = -6

//so:extern UV_EMLINK
const EMLINK = -31

//so:extern UV_EHOSTDOWN
const EHOSTDOWN = -64

//so:extern UV_EREMOTEIO
const EREMOTEIO = -4030

//so:extern UV_ENOTTY
const ENOTTY = -25

//so:extern UV_EFTYPE
const EFTYPE = -79

//so:extern UV_EILSEQ
const EILSEQ = -92

//so:extern UV_ESOCKTNOSUPPORT
const ESOCKTNOSUPPORT = -44

//so:extern UV_ENODATA
const ENODATA = -96

//so:extern UV_EUNATCH
const EUNATCH = -4023

//so:extern UV_ENOEXEC
const ENOEXEC = -8

//so:extern UV_ERRNO_MAX
const ERRNO_MAX = -4096

//so:extern UV_UNKNOWN_HANDLE
const UNKNOWN_HANDLE = 0

//so:extern UV_ASYNC
const ASYNC = 1

//so:extern UV_CHECK
const CHECK = 2

//so:extern UV_FS_EVENT
const FS_EVENT = 3

//so:extern UV_FS_POLL
const FS_POLL = 4

//so:extern UV_HANDLE
const HANDLE = 5

//so:extern UV_IDLE
const IDLE = 6

//so:extern UV_NAMED_PIPE
const NAMED_PIPE = 7

//so:extern UV_POLL
const POLL = 8

//so:extern UV_PREPARE
const PREPARE = 9

//so:extern UV_PROCESS
const PROCESS = 10

//so:extern UV_STREAM
const STREAM = 11

//so:extern UV_TCP
const TCP = 12

//so:extern UV_TIMER
const TIMER = 13

//so:extern UV_TTY
const TTY = 14

//so:extern UV_UDP
const UDP = 15

//so:extern UV_SIGNAL
const SIGNAL = 16

//so:extern UV_FILE
const UV_FILE = 17

//so:extern UV_HANDLE_TYPE_MAX
const HANDLE_TYPE_MAX = 18

//so:extern UV_UNKNOWN_REQ
const UNKNOWN_REQ = 0

//so:extern UV_REQ
const REQ = 1

//so:extern UV_CONNECT
const CONNECT = 2

//so:extern UV_WRITE
const WRITE = 3

//so:extern UV_SHUTDOWN
const SHUTDOWN = 4

//so:extern UV_UDP_SEND
const UDP_SEND = 5

//so:extern UV_FS
const FS = 6

//so:extern UV_WORK
const WORK = 7

//so:extern UV_GETADDRINFO
const GETADDRINFO = 8

//so:extern UV_GETNAMEINFO
const GETNAMEINFO = 9

//so:extern UV_RANDOM
const RANDOM = 10

//so:extern UV_REQ_TYPE_MAX
const REQ_TYPE_MAX = 11

//so:extern UV_LOOP_BLOCK_SIGNAL
const LOOP_BLOCK_SIGNAL = 0

//so:extern UV_METRICS_IDLE_TIME
const METRICS_IDLE_TIME = 1

//so:extern UV_LOOP_USE_IO_URING_SQPOLL
const LOOP_USE_IO_URING_SQPOLL = 2

//so:extern UV_RUN_DEFAULT
const RUN_DEFAULT = 0

//so:extern UV_RUN_ONCE
const RUN_ONCE = 1

//so:extern UV_RUN_NOWAIT
const RUN_NOWAIT = 2

//so:extern UV_CLOCK_MONOTONIC
const CLOCK_MONOTONIC = 0

//so:extern UV_CLOCK_REALTIME
const CLOCK_REALTIME = 1

//so:extern UV_LEAVE_GROUP
const LEAVE_GROUP = 0

//so:extern UV_JOIN_GROUP
const JOIN_GROUP = 1

//so:extern UV_TCP_IPV6ONLY
const TCP_IPV6ONLY = 1

//so:extern UV_TCP_REUSEPORT
const TCP_REUSEPORT = 2

//so:extern UV_UDP_IPV6ONLY
const UDP_IPV6ONLY = 1

//so:extern UV_UDP_PARTIAL
const UDP_PARTIAL = 2

//so:extern UV_UDP_REUSEADDR
const UDP_REUSEADDR = 4

//so:extern UV_UDP_MMSG_CHUNK
const UDP_MMSG_CHUNK = 8

//so:extern UV_UDP_MMSG_FREE
const UDP_MMSG_FREE = 16

//so:extern UV_UDP_LINUX_RECVERR
const UDP_LINUX_RECVERR = 32

//so:extern UV_UDP_REUSEPORT
const UDP_REUSEPORT = 64

//so:extern UV_UDP_RECVMMSG
const UDP_RECVMMSG = 256

//so:extern UV_TTY_MODE_NORMAL
const TTY_MODE_NORMAL = 0

//so:extern UV_TTY_MODE_RAW
const TTY_MODE_RAW = 1

//so:extern UV_TTY_MODE_IO
const TTY_MODE_IO = 2

//so:extern UV_TTY_MODE_RAW_VT
const TTY_MODE_RAW_VT = 3

//so:extern UV_TTY_SUPPORTED
const TTY_SUPPORTED = 0

//so:extern UV_TTY_UNSUPPORTED
const TTY_UNSUPPORTED = 1

//so:extern UV_PIPE_NO_TRUNCATE
const PIPE_NO_TRUNCATE = 1

//so:extern UV_READABLE
const READABLE = 1

//so:extern UV_WRITABLE
const WRITABLE = 2

//so:extern UV_DISCONNECT
const DISCONNECT = 4

//so:extern UV_PRIORITIZED
const PRIORITIZED = 8

//so:extern UV_IGNORE
const IGNORE = 0

//so:extern UV_CREATE_PIPE
const CREATE_PIPE = 1

//so:extern UV_INHERIT_FD
const INHERIT_FD = 2

//so:extern UV_INHERIT_STREAM
const INHERIT_STREAM = 4

//so:extern UV_READABLE_PIPE
const READABLE_PIPE = 16

//so:extern UV_WRITABLE_PIPE
const WRITABLE_PIPE = 32

//so:extern UV_NONBLOCK_PIPE
const NONBLOCK_PIPE = 64

//so:extern UV_OVERLAPPED_PIPE
const OVERLAPPED_PIPE = 64

//so:extern UV_PROCESS_SETUID
const PROCESS_SETUID = 1

//so:extern UV_PROCESS_SETGID
const PROCESS_SETGID = 2

//so:extern UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS
const PROCESS_WINDOWS_VERBATIM_ARGUMENTS = 4

//so:extern UV_PROCESS_DETACHED
const PROCESS_DETACHED = 8

//so:extern UV_PROCESS_WINDOWS_HIDE
const PROCESS_WINDOWS_HIDE = 16

//so:extern UV_PROCESS_WINDOWS_HIDE_CONSOLE
const PROCESS_WINDOWS_HIDE_CONSOLE = 32

//so:extern UV_PROCESS_WINDOWS_HIDE_GUI
const PROCESS_WINDOWS_HIDE_GUI = 64

//so:extern UV_PROCESS_WINDOWS_FILE_PATH_EXACT_NAME
const PROCESS_WINDOWS_FILE_PATH_EXACT_NAME = 128

//so:extern UV_DIRENT_UNKNOWN
const DIRENT_UNKNOWN = 0

//so:extern UV_DIRENT_FILE
const DIRENT_FILE = 1

//so:extern UV_DIRENT_DIR
const DIRENT_DIR = 2

//so:extern UV_DIRENT_LINK
const DIRENT_LINK = 3

//so:extern UV_DIRENT_FIFO
const DIRENT_FIFO = 4

//so:extern UV_DIRENT_SOCKET
const DIRENT_SOCKET = 5

//so:extern UV_DIRENT_CHAR
const DIRENT_CHAR = 6

//so:extern UV_DIRENT_BLOCK
const DIRENT_BLOCK = 7

//so:extern UV_FS_UNKNOWN
const FS_UNKNOWN = -1

//so:extern UV_FS_CUSTOM
const FS_CUSTOM = 0

//so:extern UV_FS_OPEN
const FS_OPEN = 1

//so:extern UV_FS_CLOSE
const FS_CLOSE = 2

//so:extern UV_FS_READ
const FS_READ = 3

//so:extern UV_FS_WRITE
const FS_WRITE = 4

//so:extern UV_FS_SENDFILE
const FS_SENDFILE = 5

//so:extern UV_FS_STAT
const FS_STAT = 6

//so:extern UV_FS_LSTAT
const FS_LSTAT = 7

//so:extern UV_FS_FSTAT
const FS_FSTAT = 8

//so:extern UV_FS_FTRUNCATE
const FS_FTRUNCATE = 9

//so:extern UV_FS_UTIME
const FS_UTIME = 10

//so:extern UV_FS_FUTIME
const FS_FUTIME = 11

//so:extern UV_FS_ACCESS
const FS_ACCESS = 12

//so:extern UV_FS_CHMOD
const FS_CHMOD = 13

//so:extern UV_FS_FCHMOD
const FS_FCHMOD = 14

//so:extern UV_FS_FSYNC
const FS_FSYNC = 15

//so:extern UV_FS_FDATASYNC
const FS_FDATASYNC = 16

//so:extern UV_FS_UNLINK
const FS_UNLINK = 17

//so:extern UV_FS_RMDIR
const FS_RMDIR = 18

//so:extern UV_FS_MKDIR
const FS_MKDIR = 19

//so:extern UV_FS_MKDTEMP
const FS_MKDTEMP = 20

//so:extern UV_FS_RENAME
const FS_RENAME = 21

//so:extern UV_FS_SCANDIR
const FS_SCANDIR = 22

//so:extern UV_FS_LINK
const FS_LINK = 23

//so:extern UV_FS_SYMLINK
const FS_SYMLINK = 24

//so:extern UV_FS_READLINK
const FS_READLINK = 25

//so:extern UV_FS_CHOWN
const FS_CHOWN = 26

//so:extern UV_FS_FCHOWN
const FS_FCHOWN = 27

//so:extern UV_FS_REALPATH
const FS_REALPATH = 28

//so:extern UV_FS_COPYFILE
const FS_COPYFILE = 29

//so:extern UV_FS_LCHOWN
const FS_LCHOWN = 30

//so:extern UV_FS_OPENDIR
const FS_OPENDIR = 31

//so:extern UV_FS_READDIR
const FS_READDIR = 32

//so:extern UV_FS_CLOSEDIR
const FS_CLOSEDIR = 33

//so:extern UV_FS_STATFS
const FS_STATFS = 34

//so:extern UV_FS_MKSTEMP
const FS_MKSTEMP = 35

//so:extern UV_FS_LUTIME
const FS_LUTIME = 36

//so:extern UV_RENAME
const RENAME = 1

//so:extern UV_CHANGE
const CHANGE = 2

//so:extern UV_FS_EVENT_WATCH_ENTRY
const FS_EVENT_WATCH_ENTRY = 1

//so:extern UV_FS_EVENT_STAT
const FS_EVENT_STAT = 2

//so:extern UV_FS_EVENT_RECURSIVE
const FS_EVENT_RECURSIVE = 4

//so:extern UV_THREAD_NO_FLAGS
const THREAD_NO_FLAGS = 0

//so:extern UV_THREAD_HAS_STACK_SIZE
const THREAD_HAS_STACK_SIZE = 1

//so:extern UV_FS_COPYFILE_EXCL
const FS_COPYFILE_EXCL = 1

//so:extern UV_FS_COPYFILE_FICLONE
const FS_COPYFILE_FICLONE = 2

//so:extern UV_FS_COPYFILE_FICLONE_FORCE
const FS_COPYFILE_FICLONE_FORCE = 4

//so:extern UV_FS_O_APPEND
const FS_O_APPEND = 8

//so:extern UV_FS_O_CREAT
const FS_O_CREAT = 512

//so:extern UV_FS_O_DIRECT
const FS_O_DIRECT = 0

//so:extern UV_FS_O_DIRECTORY
const FS_O_DIRECTORY = 1048576

//so:extern UV_FS_O_DSYNC
const FS_O_DSYNC = 4194304

//so:extern UV_FS_O_EXCL
const FS_O_EXCL = 2048

//so:extern UV_FS_O_EXLOCK
const FS_O_EXLOCK = 32

//so:extern UV_FS_O_FILEMAP
const FS_O_FILEMAP = 0

//so:extern UV_FS_O_NOATIME
const FS_O_NOATIME = 0

//so:extern UV_FS_O_NOCTTY
const FS_O_NOCTTY = 131072

//so:extern UV_FS_O_NOFOLLOW
const FS_O_NOFOLLOW = 256

//so:extern UV_FS_O_NONBLOCK
const FS_O_NONBLOCK = 4

//so:extern UV_FS_O_RANDOM
const FS_O_RANDOM = 0

//so:extern UV_FS_O_RDONLY
const FS_O_RDONLY = 0

//so:extern UV_FS_O_RDWR
const FS_O_RDWR = 2

//so:extern UV_FS_O_SEQUENTIAL
const FS_O_SEQUENTIAL = 0

//so:extern UV_FS_O_SHORT_LIVED
const FS_O_SHORT_LIVED = 0

//so:extern UV_FS_O_SYMLINK
const FS_O_SYMLINK = 2097152

//so:extern UV_FS_O_SYNC
const FS_O_SYNC = 128

//so:extern UV_FS_O_TEMPORARY
const FS_O_TEMPORARY = 0

//so:extern UV_FS_O_TRUNC
const FS_O_TRUNC = 1024

//so:extern UV_FS_O_WRONLY
const FS_O_WRONLY = 1

//so:extern UV_FS_SYMLINK_DIR
const FS_SYMLINK_DIR = 1

//so:extern UV_FS_SYMLINK_JUNCTION
const FS_SYMLINK_JUNCTION = 2

//so:extern UV_HAVE_KQUEUE
const HAVE_KQUEUE = 1

//so:extern UV_IF_NAMESIZE
const IF_NAMESIZE = 17

//so:extern UV_MAXHOSTNAMESIZE
const MAXHOSTNAMESIZE = 257

//so:extern UV_PRIORITY_ABOVE_NORMAL
const PRIORITY_ABOVE_NORMAL = -7

//so:extern UV_PRIORITY_BELOW_NORMAL
const PRIORITY_BELOW_NORMAL = 10

//so:extern UV_PRIORITY_HIGH
const PRIORITY_HIGH = -14

//so:extern UV_PRIORITY_HIGHEST
const PRIORITY_HIGHEST = -20

//so:extern UV_PRIORITY_LOW
const PRIORITY_LOW = 19

//so:extern UV_PRIORITY_NORMAL
const PRIORITY_NORMAL = 0

//so:extern UV_VERSION_HEX
const VERSION_HEX = 78849

//so:extern UV_VERSION_IS_RELEASE
const VERSION_IS_RELEASE = 1

//so:extern UV_VERSION_MAJOR
const VERSION_MAJOR = 1

//so:extern UV_VERSION_MINOR
const VERSION_MINOR = 52

//so:extern UV_VERSION_PATCH
const VERSION_PATCH = 1

//so:extern UV__DT_BLOCK
const UV__DT_BLOCK = 6

//so:extern UV__DT_CHAR
const UV__DT_CHAR = 2

//so:extern UV__DT_DIR
const UV__DT_DIR = 4

//so:extern UV__DT_FIFO
const UV__DT_FIFO = 1

//so:extern UV__DT_FILE
const UV__DT_FILE = 8

//so:extern UV__DT_LINK
const UV__DT_LINK = 10

//so:extern UV__DT_SOCKET
const UV__DT_SOCKET = 12

//so:extern UV__EAI_ADDRFAMILY
const UV__EAI_ADDRFAMILY = -3000

//so:extern UV__EAI_AGAIN
const UV__EAI_AGAIN = -3001

//so:extern UV__EAI_BADFLAGS
const UV__EAI_BADFLAGS = -3002

//so:extern UV__EAI_BADHINTS
const UV__EAI_BADHINTS = -3013

//so:extern UV__EAI_CANCELED
const UV__EAI_CANCELED = -3003

//so:extern UV__EAI_FAIL
const UV__EAI_FAIL = -3004

//so:extern UV__EAI_FAMILY
const UV__EAI_FAMILY = -3005

//so:extern UV__EAI_MEMORY
const UV__EAI_MEMORY = -3006

//so:extern UV__EAI_NODATA
const UV__EAI_NODATA = -3007

//so:extern UV__EAI_NONAME
const UV__EAI_NONAME = -3008

//so:extern UV__EAI_OVERFLOW
const UV__EAI_OVERFLOW = -3009

//so:extern UV__EAI_PROTOCOL
const UV__EAI_PROTOCOL = -3014

//so:extern UV__EAI_SERVICE
const UV__EAI_SERVICE = -3010

//so:extern UV__EAI_SOCKTYPE
const UV__EAI_SOCKTYPE = -3011

//so:extern UV__ECHARSET
const UV__ECHARSET = -4080

//so:extern UV__ENONET
const UV__ENONET = -4056

//so:extern UV__EOF
const UV__EOF = -4095

//so:extern UV__EREMOTEIO
const UV__EREMOTEIO = -4030

//so:extern UV__EUNATCH
const UV__EUNATCH = -4023

//so:extern UV__UNKNOWN
const UV__UNKNOWN = -4094

//so:extern UV_VERSION_SUFFIX
var VERSION_SUFFIX *c.ConstChar // ""

//so:extern uv_version
func Version() c.UInt

//so:extern uv_version_string
func Version_string() *c.ConstChar

//so:extern uv_library_shutdown
func Library_shutdown()

//so:extern uv_replace_allocator
func Replace_allocator(malloc_func func(c.Size) any, realloc_func func(any, c.Size) any, calloc_func func(c.Size, c.Size) any, free_func func(any)) c.Int

//so:extern uv_default_loop
func Default_loop() *Loop_t

//so:extern uv_loop_init
func Loop_init(loop *Loop_t) c.Int

//so:extern uv_loop_close
func Loop_close(loop *Loop_t) c.Int

//so:extern uv_loop_new
func Loop_new() *Loop_t

//so:extern uv_loop_delete
func Loop_delete(arg0 *Loop_t)

//so:extern uv_loop_size
func Loop_size() c.Size

//so:extern uv_loop_alive
func Loop_alive(loop *Loop_t) c.Int

//so:extern uv_loop_configure
func Loop_configure(loop *Loop_t, option c.Int, args ...any) c.Int

//so:extern uv_loop_fork
func Loop_fork(loop *Loop_t) c.Int

//so:extern uv_run
func Run(arg0 *Loop_t, mode c.Int) c.Int

//so:extern uv_stop
func Stop(arg0 *Loop_t)

//so:extern uv_ref
func Ref(arg0 *Handle_t)

//so:extern uv_unref
func Unref(arg0 *Handle_t)

//so:extern uv_has_ref
func Has_ref(arg0 *Handle_t) c.Int

//so:extern uv_update_time
func Update_time(arg0 *Loop_t)

//so:extern uv_now
func Now(arg0 *Loop_t) uint64

//so:extern uv_backend_fd
func Backend_fd(arg0 *Loop_t) c.Int

//so:extern uv_backend_timeout
func Backend_timeout(arg0 *Loop_t) c.Int

//so:extern uv_translate_sys_error
func Translate_sys_error(sys_errno c.Int) c.Int

//so:extern uv_strerror
func Strerror(err c.Int) *c.ConstChar

//so:extern uv_strerror_r
func Strerror_r(err c.Int, buf *c.Char, buflen c.Size) *c.Char

//so:extern uv_err_name
func Err_name(err c.Int) *c.ConstChar

//so:extern uv_err_name_r
func Err_name_r(err c.Int, buf *c.Char, buflen c.Size) *c.Char

//so:extern uv_shutdown
func Shutdown(req *Shutdown_t, handle *Stream_t, cb func(*Shutdown_t, c.Int)) c.Int

//so:extern uv_handle_size
func Handle_size(type_ c.Int) c.Size

//so:extern uv_handle_get_type
func Handle_get_type(handle *Handle_t) c.Int

//so:extern uv_handle_type_name
func Handle_type_name(type_ c.Int) *c.ConstChar

//so:extern uv_handle_get_data
func Handle_get_data(handle *Handle_t) any

//so:extern uv_handle_get_loop
func Handle_get_loop(handle *Handle_t) *Loop_t

//so:extern uv_handle_set_data
func Handle_set_data(handle *Handle_t, data any)

//so:extern uv_req_size
func Req_size(type_ c.Int) c.Size

//so:extern uv_req_get_data
func Req_get_data(req *Req_t) any

//so:extern uv_req_set_data
func Req_set_data(req *Req_t, data any)

//so:extern uv_req_get_type
func Req_get_type(req *Req_t) c.Int

//so:extern uv_req_type_name
func Req_type_name(type_ c.Int) *c.ConstChar

//so:extern uv_is_active
func Is_active(handle *Handle_t) c.Int

//so:extern uv_walk
func Walk(loop *Loop_t, walk_cb func(*Handle_t, any), arg any)

//so:extern uv_print_all_handles
func Print_all_handles(loop *Loop_t, stream *FILE)

//so:extern uv_print_active_handles
func Print_active_handles(loop *Loop_t, stream *FILE)

//so:extern uv_close
func Close(handle *Handle_t, close_cb func(*Handle_t))

//so:extern uv_send_buffer_size
func Send_buffer_size(handle *Handle_t, value *c.Int) c.Int

//so:extern uv_recv_buffer_size
func Recv_buffer_size(handle *Handle_t, value *c.Int) c.Int

//so:extern uv_fileno
func Fileno(handle *Handle_t, fd *c.Int) c.Int

//so:extern uv_buf_init
func Buf_init(base *c.Char, len c.UInt) Buf_t

//so:extern uv_pipe
func Pipe(fds *c.Int, read_flags c.Int, write_flags c.Int) c.Int

//so:extern uv_socketpair
func Socketpair(type_ c.Int, protocol c.Int, socket_vector *c.Int, flags0 c.Int, flags1 c.Int) c.Int

//so:extern uv_stream_get_write_queue_size
func Stream_get_write_queue_size(stream *Stream_t) c.Size

//so:extern uv_listen
func Listen(stream *Stream_t, backlog c.Int, cb func(*Stream_t, c.Int)) c.Int

//so:extern uv_accept
func Accept(server *Stream_t, client *Stream_t) c.Int

//so:extern uv_read_start
func Read_start(arg0 *Stream_t, alloc_cb func(*Handle_t, c.Size, *Buf_t), read_cb func(*Stream_t, c.SSize, *ConstBuf_t)) c.Int

//so:extern uv_read_stop
func Read_stop(arg0 *Stream_t) c.Int

//so:extern uv_write
func Write(req *Write_t, handle *Stream_t, bufs *Buf_t, nbufs c.UInt, cb func(*Write_t, c.Int)) c.Int

//so:extern uv_write2
func Write2(req *Write_t, handle *Stream_t, bufs *Buf_t, nbufs c.UInt, send_handle *Stream_t, cb func(*Write_t, c.Int)) c.Int

//so:extern uv_try_write
func Try_write(handle *Stream_t, bufs *Buf_t, nbufs c.UInt) c.Int

//so:extern uv_try_write2
func Try_write2(handle *Stream_t, bufs *Buf_t, nbufs c.UInt, send_handle *Stream_t) c.Int

//so:extern uv_is_readable
func Is_readable(handle *Stream_t) c.Int

//so:extern uv_is_writable
func Is_writable(handle *Stream_t) c.Int

//so:extern uv_stream_set_blocking
func Stream_set_blocking(handle *Stream_t, blocking c.Int) c.Int

//so:extern uv_is_closing
func Is_closing(handle *Handle_t) c.Int

//so:extern uv_tcp_init
func Tcp_init(arg0 *Loop_t, handle *Tcp_t) c.Int

//so:extern uv_tcp_init_ex
func Tcp_init_ex(arg0 *Loop_t, handle *Tcp_t, flags c.UInt) c.Int

//so:extern uv_tcp_open
func Tcp_open(handle *Tcp_t, sock c.Int) c.Int

//so:extern uv_tcp_nodelay
func Tcp_nodelay(handle *Tcp_t, enable c.Int) c.Int

//so:extern uv_tcp_keepalive
func Tcp_keepalive(handle *Tcp_t, enable c.Int, delay c.UInt) c.Int

//so:extern uv_tcp_keepalive_ex
func Tcp_keepalive_ex(handle *Tcp_t, on c.Int, idle c.UInt, intvl c.UInt, cnt c.UInt) c.Int

//so:extern uv_tcp_simultaneous_accepts
func Tcp_simultaneous_accepts(handle *Tcp_t, enable c.Int) c.Int

//so:extern uv_tcp_bind
func Tcp_bind(handle *Tcp_t, addr *Sockaddr, flags c.UInt) c.Int

//so:extern uv_tcp_getsockname
func Tcp_getsockname(handle *Tcp_t, name *Sockaddr, namelen *c.Int) c.Int

//so:extern uv_tcp_getpeername
func Tcp_getpeername(handle *Tcp_t, name *Sockaddr, namelen *c.Int) c.Int

//so:extern uv_tcp_close_reset
func Tcp_close_reset(handle *Tcp_t, close_cb func(*Handle_t)) c.Int

//so:extern uv_tcp_connect
func Tcp_connect(req *Connect_t, handle *Tcp_t, addr *Sockaddr, cb func(*Connect_t, c.Int)) c.Int

//so:extern uv_udp_init
func Udp_init(arg0 *Loop_t, handle *Udp_t) c.Int

//so:extern uv_udp_init_ex
func Udp_init_ex(arg0 *Loop_t, handle *Udp_t, flags c.UInt) c.Int

//so:extern uv_udp_open
func Udp_open(handle *Udp_t, sock c.Int) c.Int

//so:extern uv_udp_open_ex
func Udp_open_ex(handle *Udp_t, sock c.Int, flags c.UInt) c.Int

//so:extern uv_udp_bind
func Udp_bind(handle *Udp_t, addr *Sockaddr, flags c.UInt) c.Int

//so:extern uv_udp_connect
func Udp_connect(handle *Udp_t, addr *Sockaddr) c.Int

//so:extern uv_udp_getpeername
func Udp_getpeername(handle *Udp_t, name *Sockaddr, namelen *c.Int) c.Int

//so:extern uv_udp_getsockname
func Udp_getsockname(handle *Udp_t, name *Sockaddr, namelen *c.Int) c.Int

//so:extern uv_udp_set_membership
func Udp_set_membership(handle *Udp_t, multicast_addr string, interface_addr string, membership c.Int) c.Int

//so:extern uv_udp_set_source_membership
func Udp_set_source_membership(handle *Udp_t, multicast_addr string, interface_addr string, source_addr string, membership c.Int) c.Int

//so:extern uv_udp_set_multicast_loop
func Udp_set_multicast_loop(handle *Udp_t, on c.Int) c.Int

//so:extern uv_udp_set_multicast_ttl
func Udp_set_multicast_ttl(handle *Udp_t, ttl c.Int) c.Int

//so:extern uv_udp_set_multicast_interface
func Udp_set_multicast_interface(handle *Udp_t, interface_addr string) c.Int

//so:extern uv_udp_set_broadcast
func Udp_set_broadcast(handle *Udp_t, on c.Int) c.Int

//so:extern uv_udp_set_ttl
func Udp_set_ttl(handle *Udp_t, ttl c.Int) c.Int

//so:extern uv_udp_send
func Udp_send(req *Udp_send_t, handle *Udp_t, bufs *Buf_t, nbufs c.UInt, addr *Sockaddr, send_cb func(*Udp_send_t, c.Int)) c.Int

//so:extern uv_udp_try_send
func Udp_try_send(handle *Udp_t, bufs *Buf_t, nbufs c.UInt, addr *Sockaddr) c.Int

//so:extern uv_udp_try_send2
func Udp_try_send2(handle *Udp_t, count c.UInt, bufs **Buf_t, nbufs *c.UInt, addrs **Sockaddr, flags c.UInt) c.Int

//so:extern uv_udp_recv_start
func Udp_recv_start(handle *Udp_t, alloc_cb func(*Handle_t, c.Size, *Buf_t), recv_cb func(*Udp_t, c.SSize, *ConstBuf_t, *ConstSockaddr, c.UInt)) c.Int

//so:extern uv_udp_using_recvmmsg
func Udp_using_recvmmsg(handle *Udp_t) c.Int

//so:extern uv_udp_recv_stop
func Udp_recv_stop(handle *Udp_t) c.Int

//so:extern uv_udp_get_send_queue_size
func Udp_get_send_queue_size(handle *Udp_t) c.Size

//so:extern uv_udp_get_send_queue_count
func Udp_get_send_queue_count(handle *Udp_t) c.Size

//so:extern uv_tty_init
func Tty_init(arg0 *Loop_t, arg1 *Tty_t, fd c.Int, readable c.Int) c.Int

//so:extern uv_tty_set_mode
func Tty_set_mode(arg0 *Tty_t, mode c.Int) c.Int

//so:extern uv_tty_reset_mode
func Tty_reset_mode() c.Int

//so:extern uv_tty_get_winsize
func Tty_get_winsize(arg0 *Tty_t, width *c.Int, height *c.Int) c.Int

//so:extern uv_tty_set_vterm_state
func Tty_set_vterm_state(state c.Int)

//so:extern uv_tty_get_vterm_state
func Tty_get_vterm_state(state *c.Int) c.Int

//so:extern uv_guess_handle
func Guess_handle(file c.Int) c.Int

//so:extern uv_pipe_init
func Pipe_init(arg0 *Loop_t, handle *Pipe_t, ipc c.Int) c.Int

//so:extern uv_pipe_open
func Pipe_open(arg0 *Pipe_t, file c.Int) c.Int

//so:extern uv_pipe_bind
func Pipe_bind(handle *Pipe_t, name string) c.Int

//so:extern uv_pipe_bind2
func Pipe_bind2(handle *Pipe_t, name string, namelen c.Size, flags c.UInt) c.Int

//so:extern uv_pipe_connect
func Pipe_connect(req *Connect_t, handle *Pipe_t, name string, cb func(*Connect_t, c.Int))

//so:extern uv_pipe_connect2
func Pipe_connect2(req *Connect_t, handle *Pipe_t, name string, namelen c.Size, flags c.UInt, cb func(*Connect_t, c.Int)) c.Int

//so:extern uv_pipe_getsockname
func Pipe_getsockname(handle *Pipe_t, buffer *c.Char, size *c.Size) c.Int

//so:extern uv_pipe_getpeername
func Pipe_getpeername(handle *Pipe_t, buffer *c.Char, size *c.Size) c.Int

//so:extern uv_pipe_pending_instances
func Pipe_pending_instances(handle *Pipe_t, count c.Int)

//so:extern uv_pipe_pending_count
func Pipe_pending_count(handle *Pipe_t) c.Int

//so:extern uv_pipe_pending_type
func Pipe_pending_type(handle *Pipe_t) c.Int

//so:extern uv_pipe_chmod
func Pipe_chmod(handle *Pipe_t, flags c.Int) c.Int

//so:extern uv_poll_init
func Poll_init(loop *Loop_t, handle *Poll_t, fd c.Int) c.Int

//so:extern uv_poll_init_socket
func Poll_init_socket(loop *Loop_t, handle *Poll_t, socket c.Int) c.Int

//so:extern uv_poll_start
func Poll_start(handle *Poll_t, events c.Int, cb func(*Poll_t, c.Int, c.Int)) c.Int

//so:extern uv_poll_stop
func Poll_stop(handle *Poll_t) c.Int

//so:extern uv_prepare_init
func Prepare_init(arg0 *Loop_t, prepare *Prepare_t) c.Int

//so:extern uv_prepare_start
func Prepare_start(prepare *Prepare_t, cb func(*Prepare_t)) c.Int

//so:extern uv_prepare_stop
func Prepare_stop(prepare *Prepare_t) c.Int

//so:extern uv_check_init
func Check_init(arg0 *Loop_t, check *Check_t) c.Int

//so:extern uv_check_start
func Check_start(check *Check_t, cb func(*Check_t)) c.Int

//so:extern uv_check_stop
func Check_stop(check *Check_t) c.Int

//so:extern uv_idle_init
func Idle_init(arg0 *Loop_t, idle *Idle_t) c.Int

//so:extern uv_idle_start
func Idle_start(idle *Idle_t, cb func(*Idle_t)) c.Int

//so:extern uv_idle_stop
func Idle_stop(idle *Idle_t) c.Int

//so:extern uv_async_init
func Async_init(arg0 *Loop_t, async *Async_t, async_cb func(*Async_t)) c.Int

//so:extern uv_async_send
func Async_send(async *Async_t) c.Int

//so:extern uv_timer_init
func Timer_init(arg0 *Loop_t, handle *Timer_t) c.Int

//so:extern uv_timer_start
func Timer_start(handle *Timer_t, cb func(*Timer_t), timeout uint64, repeat uint64) c.Int

//so:extern uv_timer_stop
func Timer_stop(handle *Timer_t) c.Int

//so:extern uv_timer_again
func Timer_again(handle *Timer_t) c.Int

//so:extern uv_timer_set_repeat
func Timer_set_repeat(handle *Timer_t, repeat uint64)

//so:extern uv_timer_get_repeat
func Timer_get_repeat(handle *Timer_t) uint64

//so:extern uv_timer_get_due_in
func Timer_get_due_in(handle *Timer_t) uint64

//so:extern uv_getaddrinfo
func Getaddrinfo(loop *Loop_t, req *Getaddrinfo_t, getaddrinfo_cb func(*Getaddrinfo_t, c.Int, *Addrinfo), node string, service string, hints *Addrinfo) c.Int

//so:extern uv_freeaddrinfo
func Freeaddrinfo(ai *Addrinfo)

//so:extern uv_getnameinfo
func Getnameinfo(loop *Loop_t, req *Getnameinfo_t, getnameinfo_cb func(*Getnameinfo_t, c.Int, *c.ConstChar, *c.ConstChar), addr *Sockaddr, flags c.Int) c.Int

//so:extern uv_spawn
func Spawn(loop *Loop_t, handle *Process_t, options *Process_options_t) c.Int

//so:extern uv_process_kill
func Process_kill(arg0 *Process_t, signum c.Int) c.Int

//so:extern uv_kill
func Kill(pid c.Int, signum c.Int) c.Int

//so:extern uv_process_get_pid
func Process_get_pid(arg0 *Process_t) c.Int

//so:extern uv_queue_work
func Queue_work(loop *Loop_t, req *Work_t, work_cb func(*Work_t), after_work_cb func(*Work_t, c.Int)) c.Int

//so:extern uv_cancel
func Cancel(req *Req_t) c.Int

//so:extern uv_setup_args
func Setup_args(argc c.Int, argv **c.Char) **c.Char

//so:extern uv_get_process_title
func Get_process_title(buffer *c.Char, size c.Size) c.Int

//so:extern uv_set_process_title
func Set_process_title(title string) c.Int

//so:extern uv_resident_set_memory
func Resident_set_memory(rss *c.Size) c.Int

//so:extern uv_uptime
func Uptime(uptime *float64) c.Int

//so:extern uv_get_osfhandle
func Get_osfhandle(fd c.Int) c.Int

//so:extern uv_open_osfhandle
func Open_osfhandle(os_fd c.Int) c.Int

//so:extern uv_getrusage
func Getrusage(rusage *Rusage_t) c.Int

//so:extern uv_getrusage_thread
func Getrusage_thread(rusage *Rusage_t) c.Int

//so:extern uv_os_homedir
func Os_homedir(buffer *c.Char, size *c.Size) c.Int

//so:extern uv_os_tmpdir
func Os_tmpdir(buffer *c.Char, size *c.Size) c.Int

//so:extern uv_os_get_passwd
func Os_get_passwd(pwd *Passwd_t) c.Int

//so:extern uv_os_free_passwd
func Os_free_passwd(pwd *Passwd_t)

//so:extern uv_os_get_passwd2
func Os_get_passwd2(pwd *Passwd_t, uid c.UInt) c.Int

//so:extern uv_os_get_group
func Os_get_group(grp *Group_t, gid c.UInt) c.Int

//so:extern uv_os_free_group
func Os_free_group(grp *Group_t)

//so:extern uv_os_getpid
func Os_getpid() c.Int

//so:extern uv_os_getppid
func Os_getppid() c.Int

//so:extern uv_os_getpriority
func Os_getpriority(pid c.Int, priority *c.Int) c.Int

//so:extern uv_os_setpriority
func Os_setpriority(pid c.Int, priority c.Int) c.Int

//so:extern uv_thread_getpriority
func Thread_getpriority(tid *_opaque_pthread_t, priority *c.Int) c.Int

//so:extern uv_thread_setpriority
func Thread_setpriority(tid *_opaque_pthread_t, priority c.Int) c.Int

//so:extern uv_available_parallelism
func Available_parallelism() c.UInt

//so:extern uv_cpu_info
func Cpu_info(cpu_infos **Cpu_info_t, count *c.Int) c.Int

//so:extern uv_free_cpu_info
func Free_cpu_info(cpu_infos *Cpu_info_t, count c.Int)

//so:extern uv_cpumask_size
func Cpumask_size() c.Int

//so:extern uv_interface_addresses
func Interface_addresses(addresses **Interface_address_t, count *c.Int) c.Int

//so:extern uv_free_interface_addresses
func Free_interface_addresses(addresses *Interface_address_t, count c.Int)

//so:extern uv_os_environ
func Os_environ(envitems **Env_item_t, count *c.Int) c.Int

//so:extern uv_os_free_environ
func Os_free_environ(envitems *Env_item_t, count c.Int)

//so:extern uv_os_getenv
func Os_getenv(name string, buffer *c.Char, size *c.Size) c.Int

//so:extern uv_os_setenv
func Os_setenv(name string, value string) c.Int

//so:extern uv_os_unsetenv
func Os_unsetenv(name string) c.Int

//so:extern uv_os_gethostname
func Os_gethostname(buffer *c.Char, size *c.Size) c.Int

//so:extern uv_os_uname
func Os_uname(buffer *Utsname_t) c.Int

//so:extern uv_metrics_info
func Metrics_info(loop *Loop_t, metrics *Metrics_t) c.Int

//so:extern uv_metrics_idle_time
func Metrics_idle_time(loop *Loop_t) uint64

//so:extern uv_fs_get_type
func Fs_get_type(arg0 *Fs_t) c.Int

//so:extern uv_fs_get_result
func Fs_get_result(arg0 *Fs_t) c.SSize

//so:extern uv_fs_get_system_error
func Fs_get_system_error(arg0 *Fs_t) c.Int

//so:extern uv_fs_get_ptr
func Fs_get_ptr(arg0 *Fs_t) any

//so:extern uv_fs_get_path
func Fs_get_path(arg0 *Fs_t) *c.ConstChar

//so:extern uv_fs_get_statbuf
func Fs_get_statbuf(arg0 *Fs_t) *Stat_t

//so:extern uv_fs_req_cleanup
func Fs_req_cleanup(req *Fs_t)

//so:extern uv_fs_close
func Fs_close(loop *Loop_t, req *Fs_t, file c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_open
func Fs_open(loop *Loop_t, req *Fs_t, path string, flags c.Int, mode c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_read
func Fs_read(loop *Loop_t, req *Fs_t, file c.Int, bufs *Buf_t, nbufs c.UInt, offset int64, cb func(*Fs_t)) c.Int

//so:extern uv_fs_unlink
func Fs_unlink(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_write
func Fs_write(loop *Loop_t, req *Fs_t, file c.Int, bufs *Buf_t, nbufs c.UInt, offset int64, cb func(*Fs_t)) c.Int

//so:extern uv_fs_copyfile
func Fs_copyfile(loop *Loop_t, req *Fs_t, path string, new_path string, flags c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_mkdir
func Fs_mkdir(loop *Loop_t, req *Fs_t, path string, mode c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_mkdtemp
func Fs_mkdtemp(loop *Loop_t, req *Fs_t, tpl string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_mkstemp
func Fs_mkstemp(loop *Loop_t, req *Fs_t, tpl string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_rmdir
func Fs_rmdir(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_scandir
func Fs_scandir(loop *Loop_t, req *Fs_t, path string, flags c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_scandir_next
func Fs_scandir_next(req *Fs_t, ent *Dirent_t) c.Int

//so:extern uv_fs_opendir
func Fs_opendir(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_readdir
func Fs_readdir(loop *Loop_t, req *Fs_t, dir *Dir_t, cb func(*Fs_t)) c.Int

//so:extern uv_fs_closedir
func Fs_closedir(loop *Loop_t, req *Fs_t, dir *Dir_t, cb func(*Fs_t)) c.Int

//so:extern uv_fs_stat
func Fs_stat(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_fstat
func Fs_fstat(loop *Loop_t, req *Fs_t, file c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_rename
func Fs_rename(loop *Loop_t, req *Fs_t, path string, new_path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_fsync
func Fs_fsync(loop *Loop_t, req *Fs_t, file c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_fdatasync
func Fs_fdatasync(loop *Loop_t, req *Fs_t, file c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_ftruncate
func Fs_ftruncate(loop *Loop_t, req *Fs_t, file c.Int, offset int64, cb func(*Fs_t)) c.Int

//so:extern uv_fs_sendfile
func Fs_sendfile(loop *Loop_t, req *Fs_t, out_fd c.Int, in_fd c.Int, in_offset int64, length c.Size, cb func(*Fs_t)) c.Int

//so:extern uv_fs_access
func Fs_access(loop *Loop_t, req *Fs_t, path string, mode c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_chmod
func Fs_chmod(loop *Loop_t, req *Fs_t, path string, mode c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_utime
func Fs_utime(loop *Loop_t, req *Fs_t, path string, atime float64, mtime float64, cb func(*Fs_t)) c.Int

//so:extern uv_fs_futime
func Fs_futime(loop *Loop_t, req *Fs_t, file c.Int, atime float64, mtime float64, cb func(*Fs_t)) c.Int

//so:extern uv_fs_lutime
func Fs_lutime(loop *Loop_t, req *Fs_t, path string, atime float64, mtime float64, cb func(*Fs_t)) c.Int

//so:extern uv_fs_lstat
func Fs_lstat(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_link
func Fs_link(loop *Loop_t, req *Fs_t, path string, new_path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_symlink
func Fs_symlink(loop *Loop_t, req *Fs_t, path string, new_path string, flags c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_readlink
func Fs_readlink(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_realpath
func Fs_realpath(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_fchmod
func Fs_fchmod(loop *Loop_t, req *Fs_t, file c.Int, mode c.Int, cb func(*Fs_t)) c.Int

//so:extern uv_fs_chown
func Fs_chown(loop *Loop_t, req *Fs_t, path string, uid c.UInt, gid c.UInt, cb func(*Fs_t)) c.Int

//so:extern uv_fs_fchown
func Fs_fchown(loop *Loop_t, req *Fs_t, file c.Int, uid c.UInt, gid c.UInt, cb func(*Fs_t)) c.Int

//so:extern uv_fs_lchown
func Fs_lchown(loop *Loop_t, req *Fs_t, path string, uid c.UInt, gid c.UInt, cb func(*Fs_t)) c.Int

//so:extern uv_fs_statfs
func Fs_statfs(loop *Loop_t, req *Fs_t, path string, cb func(*Fs_t)) c.Int

//so:extern uv_fs_poll_init
func Fs_poll_init(loop *Loop_t, handle *Fs_poll_t) c.Int

//so:extern uv_fs_poll_start
func Fs_poll_start(handle *Fs_poll_t, poll_cb func(*Fs_poll_t, c.Int, *ConstStat_t, *ConstStat_t), path string, interval c.UInt) c.Int

//so:extern uv_fs_poll_stop
func Fs_poll_stop(handle *Fs_poll_t) c.Int

//so:extern uv_fs_poll_getpath
func Fs_poll_getpath(handle *Fs_poll_t, buffer *c.Char, size *c.Size) c.Int

//so:extern uv_signal_init
func Signal_init(loop *Loop_t, handle *Signal_t) c.Int

//so:extern uv_signal_start
func Signal_start(handle *Signal_t, signal_cb func(*Signal_t, c.Int), signum c.Int) c.Int

//so:extern uv_signal_start_oneshot
func Signal_start_oneshot(handle *Signal_t, signal_cb func(*Signal_t, c.Int), signum c.Int) c.Int

//so:extern uv_signal_stop
func Signal_stop(handle *Signal_t) c.Int

//so:extern uv_loadavg
func Loadavg(avg *float64)

//so:extern uv_fs_event_init
func Fs_event_init(loop *Loop_t, handle *Fs_event_t) c.Int

//so:extern uv_fs_event_start
func Fs_event_start(handle *Fs_event_t, cb func(*Fs_event_t, *c.ConstChar, c.Int, c.Int), path string, flags c.UInt) c.Int

//so:extern uv_fs_event_stop
func Fs_event_stop(handle *Fs_event_t) c.Int

//so:extern uv_fs_event_getpath
func Fs_event_getpath(handle *Fs_event_t, buffer *c.Char, size *c.Size) c.Int

//so:extern uv_ip4_addr
func Ip4_addr(ip string, port c.Int, addr *Sockaddr_in) c.Int

//so:extern uv_ip6_addr
func Ip6_addr(ip string, port c.Int, addr *Sockaddr_in6) c.Int

//so:extern uv_ip4_name
func Ip4_name(src *Sockaddr_in, dst *c.Char, size c.Size) c.Int

//so:extern uv_ip6_name
func Ip6_name(src *Sockaddr_in6, dst *c.Char, size c.Size) c.Int

//so:extern uv_ip_name
func Ip_name(src *Sockaddr, dst *c.Char, size c.Size) c.Int

//so:extern uv_inet_ntop
func Inet_ntop(af c.Int, src any, dst *c.Char, size c.Size) c.Int

//so:extern uv_inet_pton
func Inet_pton(af c.Int, src string, dst any) c.Int

//so:extern uv_random
func Random(loop *Loop_t, req *Random_t, buf any, buflen c.Size, flags c.UInt, cb func(*Random_t, c.Int, any, c.Size)) c.Int

//so:extern uv_if_indextoname
func If_indextoname(ifindex c.UInt, buffer *c.Char, size *c.Size) c.Int

//so:extern uv_if_indextoiid
func If_indextoiid(ifindex c.UInt, buffer *c.Char, size *c.Size) c.Int

//so:extern uv_exepath
func Exepath(buffer *c.Char, size *c.Size) c.Int

//so:extern uv_cwd
func Cwd(buffer *c.Char, size *c.Size) c.Int

//so:extern uv_chdir
func Chdir(dir string) c.Int

//so:extern uv_get_free_memory
func Get_free_memory() uint64

//so:extern uv_get_total_memory
func Get_total_memory() uint64

//so:extern uv_get_constrained_memory
func Get_constrained_memory() uint64

//so:extern uv_get_available_memory
func Get_available_memory() uint64

//so:extern uv_clock_gettime
func Clock_gettime(clock_id c.Int, ts *Timespec64_t) c.Int

//so:extern uv_hrtime
func Hrtime() uint64

//so:extern uv_sleep
func Sleep(msec c.UInt)

//so:extern uv_disable_stdio_inheritance
func Disable_stdio_inheritance()

//so:extern uv_dlopen
func Dlopen(filename string, lib *Lib_t) c.Int

//so:extern uv_dlclose
func Dlclose(lib *Lib_t)

//so:extern uv_dlsym
func Dlsym(lib *Lib_t, name string, ptr *any) c.Int

//so:extern uv_dlerror
func Dlerror(lib *Lib_t) *c.ConstChar

//so:extern uv_mutex_init
func Mutex_init(handle *Mutex_t) c.Int

//so:extern uv_mutex_init_recursive
func Mutex_init_recursive(handle *Mutex_t) c.Int

//so:extern uv_mutex_destroy
func Mutex_destroy(handle *Mutex_t)

//so:extern uv_mutex_lock
func Mutex_lock(handle *Mutex_t)

//so:extern uv_mutex_trylock
func Mutex_trylock(handle *Mutex_t) c.Int

//so:extern uv_mutex_unlock
func Mutex_unlock(handle *Mutex_t)

//so:extern uv_rwlock_init
func Rwlock_init(rwlock *Rwlock_t) c.Int

//so:extern uv_rwlock_destroy
func Rwlock_destroy(rwlock *Rwlock_t)

//so:extern uv_rwlock_rdlock
func Rwlock_rdlock(rwlock *Rwlock_t)

//so:extern uv_rwlock_tryrdlock
func Rwlock_tryrdlock(rwlock *Rwlock_t) c.Int

//so:extern uv_rwlock_rdunlock
func Rwlock_rdunlock(rwlock *Rwlock_t)

//so:extern uv_rwlock_wrlock
func Rwlock_wrlock(rwlock *Rwlock_t)

//so:extern uv_rwlock_trywrlock
func Rwlock_trywrlock(rwlock *Rwlock_t) c.Int

//so:extern uv_rwlock_wrunlock
func Rwlock_wrunlock(rwlock *Rwlock_t)

//so:extern uv_sem_init
func Sem_init(sem *c.UInt, value c.UInt) c.Int

//so:extern uv_sem_destroy
func Sem_destroy(sem *c.UInt)

//so:extern uv_sem_post
func Sem_post(sem *c.UInt)

//so:extern uv_sem_wait
func Sem_wait(sem *c.UInt)

//so:extern uv_sem_trywait
func Sem_trywait(sem *c.UInt) c.Int

//so:extern uv_cond_init
func Cond_init(cond *Cond_t) c.Int

//so:extern uv_cond_destroy
func Cond_destroy(cond *Cond_t)

//so:extern uv_cond_signal
func Cond_signal(cond *Cond_t)

//so:extern uv_cond_broadcast
func Cond_broadcast(cond *Cond_t)

//so:extern uv_barrier_init
func Barrier_init(barrier *Barrier_t, count c.UInt) c.Int

//so:extern uv_barrier_destroy
func Barrier_destroy(barrier *Barrier_t)

//so:extern uv_barrier_wait
func Barrier_wait(barrier *Barrier_t) c.Int

//so:extern uv_cond_wait
func Cond_wait(cond *Cond_t, mutex *Mutex_t)

//so:extern uv_cond_timedwait
func Cond_timedwait(cond *Cond_t, mutex *Mutex_t, timeout uint64) c.Int

//so:extern uv_once
func Once(guard *Once_t, callback func())

//so:extern uv_key_create
func Key_create(key *c.ULong) c.Int

//so:extern uv_key_delete
func Key_delete(key *c.ULong)

//so:extern uv_key_get
func Key_get(key *c.ULong) any

//so:extern uv_key_set
func Key_set(key *c.ULong, value any)

//so:extern uv_gettimeofday
func Gettimeofday(tv *Timeval64_t) c.Int

//so:extern uv_thread_create
func Thread_create(tid **_opaque_pthread_t, entry func(any), arg any) c.Int

//so:extern uv_thread_detach
func Thread_detach(tid **_opaque_pthread_t) c.Int

//so:extern uv_thread_create_ex
func Thread_create_ex(tid **_opaque_pthread_t, params *Thread_options_t, entry func(any), arg any) c.Int

//so:extern uv_thread_setaffinity
func Thread_setaffinity(tid **_opaque_pthread_t, cpumask *c.Char, oldmask *c.Char, mask_size c.Size) c.Int

//so:extern uv_thread_getaffinity
func Thread_getaffinity(tid **_opaque_pthread_t, cpumask *c.Char, mask_size c.Size) c.Int

//so:extern uv_thread_getcpu
func Thread_getcpu() c.Int

//so:extern uv_thread_self
func Thread_self() *_opaque_pthread_t

//so:extern uv_thread_join
func Thread_join(tid **_opaque_pthread_t) c.Int

//so:extern uv_thread_equal
func Thread_equal(t1 **_opaque_pthread_t, t2 **_opaque_pthread_t) c.Int

//so:extern uv_thread_setname
func Thread_setname(name string) c.Int

//so:extern uv_thread_getname
func Thread_getname(tid **_opaque_pthread_t, name *c.Char, size c.Size) c.Int

//so:extern uv_loop_get_data
func Loop_get_data(arg0 *Loop_t) any

//so:extern uv_loop_set_data
func Loop_set_data(arg0 *Loop_t, data any)

//so:extern uv_utf16_length_as_wtf8
func Utf16_length_as_wtf8(utf16 *uint16, utf16_len c.SSize) c.Size

//so:extern uv_utf16_to_wtf8
func Utf16_to_wtf8(utf16 *uint16, utf16_len c.SSize, wtf8_ptr **c.Char, wtf8_len_ptr *c.Size) c.Int

//so:extern uv_wtf8_length_as_utf16
func Wtf8_length_as_utf16(wtf8 string) c.SSize

//so:extern uv_wtf8_to_utf16
func Wtf8_to_utf16(wtf8 string, utf16 *uint16, utf16_len c.Size)
